[package]
name = "neocogi"
version = "0.1.9"
edition = "2018"
license = "BSD-3-Clause"
authors = ["Raja Lehtihet <raja.lehtihet@gmail.com>", "Wael El Oraiby <wael.eloraiby@gmail.com>"]
description = "neocogi rendering lib"
repository = "https://github.com/NeoCogi/neocogi"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs-math3d = "0.9.16"
rs-ctypes = "0.1.1"
glfw = { version="0.43.0", default-features=false, optional=true }
egui = { version = "0.16.0", default-features=false, optional=true }

[build-dependencies]
gl_generator = "0.14.0"

[features]
default = ["renderer", "ui", "with-fonts"]
renderer = []
ui = ["renderer", "glfw", "egui", "egui/multi_threaded"]
with-fonts=["ui", "egui/default_fonts"]
