[package]
name = "nc-renderer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs-math3d = "0.9.15"
rs-ctypes = "0.1.1"
gl = "0.14.0"
