name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: sudo apt-get update && sudo apt-get install -y libglfw3-dev libgles2-mesa-dev libegl1-mesa-dev
    - name: Build
      run: cargo build --verbose
    - name: Build UI
      run: cargo build --verbose --example ui
    - name: Build Triangle
      run: cargo build --verbose --example triangle
    - name: Build Grid
      run: cargo build --verbose --example grid
    - name: Run tests
      run: cargo test --verbose
